### ISSUE TITLE
Unable to Roll Macros

### ISSUE THREAD

**Issue by sturteva** [sturteva/pf2e-random-encounters-and-weather#1]
Both the QftFF Random Encounters Macro and RandWeather-NorthernSagaLands macro, the Dialog does not properly handle "getIndex" and does not allow the "roll" button to be properly pressed

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getIndex')
[Detected 1 package: system:pf2e]
    at Object.close (eval at _executeScript (main.bundle.js:1:880947), <anonymous>:33:19)
    at Dialog.close (foundry.js:55949:38)
    at Object.onclick (foundry.js:5290:29)
    at HTMLAnchorElement.<anonymous> (foundry.js:5198:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)`

**Comment by sturteva** [comment]
Once RollTable compendium references were fixed, both macros began working as well.
